routes/web.php
<?php


Route::get('/debug','DebugController@index');


Route::group(['prefix' => 'pic', 'name' => 'pic.'], function () {
    Route::get('/public', 'PicController@public')->name('pic.public');
    Route::get('/pic/{id}', 'PicController@show')->name('pic.show');
    Route::post('/store', 'PicController@store')->name('pic.store');
    Route::post('/pic/{id}', 'PicController@update')->name('pic.update');
    Route::post('/pic/delete/{id}', 'PicController@destroy')->name('pic.destroy');
});




Route::name('admin.')->prefix('admin')->middleware(['auth'])->group(function(){

    // Auth::routes();
    //Route::get('dashboard','AdminController@index')->name('dashboard');
    Route::get('/','AdminController@index')->name('dashboard');
    Route::get('/logout', function(){
        return redirect('login')->with(Auth::logout());

    });


    ///TEMPORARY FIX




        /*--- Features Routes ---*/
        Route::group(['prefix' => 'features', 'name' => 'features.'], function () {
            Route::get('/', 'FeatureController@index')->name('features.index');
            Route::get('create', 'FeatureController@create')->name('features.create');
            Route::post('/create', 'FeatureController@store')->name('features.store');
            Route::post('update', 'FeatureController@update')->name('features.update');
            Route::delete('destroy', 'FeatureController@destroy')->name('features.destroy');
        });

//Engagement Calculator
        Route::group(['prefix' => 'calculator', 'name' => 'calculator.'], function () {
            Route::get('/', 'EngagementController@index')->name('calculator.engagement');
            //print the PDF of the engagement
            Route::post('/downloadpdf', 'EngagementController@downloadpdf')->name('calculator.downloadpdf');
        });

    /*--- Speedy Routes ---*/
    Route::group(['prefix' => 'speedy', 'name' => 'speedy.'], function () {
        Route::get('/', 'LighthouseReportController@index')->name('speedy.reports');
        Route::get('show/{id}', 'LighthouseReportController@show')->name('speedy.show');
        Route::get('create', 'LighthouseReportController@create')->name('speedy.create');
        Route::post('/', 'LighthouseReportController@store')->name('speedy.store');
        Route::get('edit/{id}', 'LighthouseReportController@edit')->name('speedy.edit');
        Route::patch('update', 'LighthouseReportController@post')->name('speedy.update');
        Route::delete('destroy', 'LighthouseReportController@destroy')->name('speedy.destroy');

        Route::post('mail', 'LighthouseReportController@send_mail_to')->name('speedy.mailto');
        Route::get('status/change/{report}', 'LighthouseReportController@change_report_status')->name('speedy.status.change');

        Route::group(['prefix' => 'preview', 'name' => 'preview.'], function () {
            Route::get('email/{id}', 'LighthouseReportController@preview_email')->name('speedy.preview.pdf');
        });

    });

    /*---Admin FAQ Routes ---*/
    Route::group(['prefix' => 'list', 'name' => 'faq.'], function () {
        Route::get('/', 'AdminFAQController@index')->name('faq.admin_list');
        Route::get('preview/{privacy?}', 'AdminFAQController@list_preview')->name('faq.preview');
        Route::get('question/{id}', 'AdminFAQController@answer_show')->name('faq.show');
        Route::patch('question/{id}', 'AdminFAQController@answer_store')->name('faq.answer_store');
        Route::delete('question/delete/{id}', 'AdminFAQController@destroy')->name('faq.destroy');
        Route::get('pending', 'AdminFAQController@pending')->name('faq.pending');
        Route::get('reports', 'AdminFAQController@reports')->name('faq.reports');
    });

    /*--- FAQ Routes ---*/
    Route::group(['prefix' => 'faq', 'name' => 'faq.'], function () {
        Route::get('/', 'FAQController@index')->name('faq.index');
        Route::post('/', "FAQController@store")->name('faq.store');
        Route::get('/search', 'FAQController@search')->name('faq.search');
        Route::get('/public', 'FAQController@public_list')->name('faq.public_list');
        Route::get('/public/search', 'FAQController@public_search')->name('faq.public_list_search');
    });


    /*--- Categories Routes ---*/
    Route::group(['prefix' => 'categories', 'name' => 'faq.'], function () {
        Route::get('/', 'CategoriesController@index')->name('category.index');
        Route::get('/category', 'CategoriesController@show')->name('category.show');
        Route::post('/category/store', 'CategoriesController@store')->name('category.store');
        Route::post('/category/{id}', 'CategoriesController@update')->name('category.update');
        Route::post('/category/delete/{id}', 'CategoriesController@destroy')->name('category.destroy');
    });


    /*--- QA Routes ---*/
    Route::group(['prefix' => 'devQA', 'name' => 'devQA.'], function () {
        Route::get('/', 'DevProjectController@index')->name('devQA.index');
        Route::get('/list', 'DevProjectController@list')->name('devQA.list');
        Route::get('/create', 'DevProjectController@create')->name('devQA.create');
        Route::post('/', 'DevProjectController@store')->name('devQA.store');
        Route::get('/{id}', 'DevProjectController@show')->name('devQA.show');
        Route::patch('/update/{id}', 'DevProjectController@update')->name('devQA.update');
        Route::post('/destroy/{id}', 'DevProjectController@destroy')->name('devQA.destroy');
        Route::post('/delete/{id}', 'DevProjectController@destroy_project_pages')->name('devQA.destroy_project_pages');
    });

    /*--- Url Routes ---*/
    Route::group(['prefix' => 'url', 'name' => 'url.'], function () {
        Route::get('/', 'UrlController@index')->name('url.index');
        Route::get('/{id}', 'UrlController@show')->name('url.show');
    });



    /*--- Contractor Routes ---*/
    Route::group(['prefix' => 'contractors', 'name' => 'contractors.'], function () {
        Route::get('/', 'DevContractorController@index')->name('contractors.index');
        Route::get('/create', 'DevContractorController@create')->name('contractors.create');
        Route::post('/', 'DevContractorController@store')->name('contractors.store');
        Route::get('/{id}', 'DevContractorController@show')->name('contractors.show');
        Route::patch('/update/{id}', 'DevContractorController@update')->name('contractors.update');
        Route::post('/destroy/{id}', 'DevContractorController@destroy')->name('contractors.destroy');
    });

    /*--- Activities Routes ---*/
    Route::group(['prefix'=>'activities','name'=>'activities.'],function(){
        Route::get('/', 'ActivityController@index')->name('activities.index');
        Route::get('show', 'ActivityController@show')->name('activities.show');
        Route::get('create', 'ActivityController@create')->name('activities.create');
        Route::post('/create', 'ActivityController@store')->name('activities.store');
        Route::post('edit', 'ActivityController@edit')->name('activities.edit');
        Route::post('update', 'ActivityController@update')->name('activities.update');
        Route::delete('destroy', 'ActivityController@destroy')->name('activities.destroy');
        
    });


    Route::group(['prefix'=>'schedule','name'=>'schedule.'],function(){
        Route::get('/', 'ScheduleController@index')->name('schedule.index');
        Route::get('/create', 'ScheduleController@create')->name('schedule.create');
        Route::post('/', 'ScheduleController@store')->name('schedule.store');
        Route::get('/show/{id}', 'ScheduleController@show')->name('schedule.show');
        Route::get('/edit/{id}', 'ScheduleController@edit')->name('schedule.edit');
        Route::patch('/{id}', 'ScheduleController@update')->name('schedule.update');
        Route::delete('/', 'ScheduleController@destroy')->name('schedule.destroy');

        Route::group(['prefix'=>'activities','name'=>'activities.'],function(){
            Route::post('/command', 'ScheduleController@get_command')->name('schedule.activities.command');
        });

        Route::post('/pageSchedule', 'ScheduleController@page_schedule')->name('schedule.page');

    });

    /*--- Page Pull Schedule Routes ---*/
    Route::group(['prefix' => 'pullSchedule', 'name' => 'pullSchedule.'], function () {
        Route::get('/', 'PullScheduleController@index')->name('pullSchedule.index');
        Route::get('/{id}/show', 'PullScheduleController@show')->name('pullSchedule.show');
        Route::post('/properties', 'PullScheduleController@get_properties')->name('pullSchedule.getProperties');
        Route::post('/pages', 'PullScheduleController@get_pages')->name('pullSchedule.getPages');
    });

    /*--- Price Buckets Routes ---*/
    Route::group(['prefix'=>'buckets','name'=>'buckets.'],function(){
        Route::get('/', 'PriceBucketController@index')->name('buckets.index');
        Route::get('/create', 'PriceBucketController@create')->name('buckets.create');
        Route::post('/', 'PriceBucketController@store')->name('buckets.store');
        //Route::get('/{id}/show', 'PriceBucketController@show')->name('buckets.show');
        //Route::post('/edit', 'PriceBucketController@edit')->name('buckets.edit');
        Route::patch('/edit', 'PriceBucketController@update')->name('buckets.update');
        Route::delete('/', 'PriceBucketController@destroy')->name('buckets.destroy');
        
    });

    /*--- Page Clients Routes ---*/
    Route::group(['prefix'=>'clients','name'=>'clients.'],function(){
        Route::get('/', 'ClientController@index')->name('clients.index');
        Route::get('/create', 'ClientController@create')->name('clients.create');
        Route::post('/', 'ClientController@store')->name('clients.store');
        Route::get('/show/{id}', 'ClientController@show')->name('clients.show');
        Route::post('/edit/{id}', 'ClientController@edit')->name('clients.edit');

app/LighthouseReport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Uuid;

class LighthouseReport extends Model
{
    use Uuid;
    use HasFactory;
    protected $keyType = 'string';
    public $incrementing = false;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo('App\LighthouseCategory', 'lighthouse_category_id', 'id');
    }

    public function status()
    {
        return $this->belongsTo('App\LighthouseStatus', 'lighthouse_status_id', 'id');
    }

    public function flags()
    {
        return $this->belongsToMany('App\LighthouseFlag', 'lighthouse_flag_reports',  'lighthouse_report_id', 'lighthouse_flag_id')->withPivot('id', 'lighthouse_report_id', 'score', 'score_normal');
    }
}

app/Http/Controllers/LighthouseReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Http;
use Illuminate\Http\Request;
use App\LighthouseReport;
use App\LighthouseCategory;
use App\LighthouseFlag;
use App\LighthouseFlagReport;
use Illuminate\Support\Facades\Auth;
use App\Property;
use App\SelectorType;
use App\MyClasses\URL;
use App\Jobs\KnobGeneration;
use App\Jobs\ExecuteLighthouseTest;
use App\Jobs\ProcessUrlsToLighthouseReports;
use App\Jobs\SendLighthouseReportEmail;
use PDF;
use App\Jobs\TestingRoberto;

class LighthouseReportController extends Controller
{
    public $dismissed_urls;
    public $invalid_urls = array();
    
    public $limit;

    public function index(){
        //render a list of a resource
        $data['user']=Auth::User();
        $data['reports']=LighthouseReport::all();
        $data['messages']=0;
        $data['comments']=0;
        $data['form_title']='Reports List';
        return view('admin.lighthouseReports.index',$data);
    }

    public function create (){
        //shows a view to create a new resource
        $data['properties']=Property::all();
        $data['selectors']=SelectorType::all();
        $data['categories']=LighthouseCategory::all();


        $data['user']=Auth::User();

        $data['messages']=0;
        $data['comments']=0;

        $data['form_centered']=true;
        $data['form_title']='Lighthouse Test';
        $data['form_submit_button_title']=$data['form_title'];
        $data['form_action']=route('admin.speedy.store');

        return view('admin.lighthouseReports.create',$data);
    }

    public function store(Request $request){



        if (Auth::user()) {   // Check is user logged in
            $this->limit = 20;
        }else{ 
            $this->limit = 1;
        }

        request()->validate([
            'url' => 'required'
        ]);
            
        $pattern = "/[\s,]+/";
        //separate the strings and create an array with the info
        $urls = preg_split($pattern, $request->url);
        
        //validate the URLs
        $valid_urls = $this->validate_urls_list($urls);
        
        //splice the valid urls to the given limit
        $accepted_urls = $this->limit_urls_array_list($valid_urls);

        if(count($valid_urls) <= 0){
            return back()->withErrors($this->invalid_urls);
        }


       for ($i=0;$i<20;$i++){
           TestingRoberto::dispatch();
       }


    //    ProcessUrlsToLighthouseReports::dispatch($accepted_urls, $request->category);
        
        //$result = $this->report_creation_cicle($accepted_urls, $request);
        
        return redirect(route('admin.speedy.reports'));

    }

    public function show($id){
        $data['user']=Auth::User();
        $data['report']=LighthouseReport::firstWhere('id', $id);
        $data['messages']=0;
        $data['comments']=0;

        return view('admin.lighthouseReports.show',$data);
    }



    public function validate_urls_list($urls){
        $valid_urls = array();
        foreach ($urls as $url) {
            if(URL::is_valid_url($url)){
                $valid_urls[] = $url;
            }else{
                $this->invalid_urls[] = $url;
            }
        }

        return $valid_urls;
    }

    //Check the number of URLs
    public function limit_urls_array_list($urls)
    {

        $urlscount = count($urls);
        $splice = $urlscount;
        //check if it's more than the limit (20)
        if($urlscount > $this->limit){
            $splice = $this->limit;
        }
        $this->dismissed_urls =  array_splice($urls, $splice);
        return $urls;

    }


    public function report_creation_cicle($urls, $request){
        (Auth::user()) ? $type = 'User' : $type = 'Admin';

        foreach ($urls as $url) {


            $report = LighthouseReport::firstWhere('url', $url);
            if(!$report){
                $this->store_report_to_database($url, $request);
            }else{
                if (!Auth::user()) {
                    return $report->id;
                }
            }
        }
    }

    Public function store_report_to_database($url, $request){
        if (Auth::user()) {   // Check is user logged in
            $type = 'User';
        }else{ 
            $type = 'Client';
        }
        $report= LighthouseReport::create([
            'url' => $url,
            'lighthouse_category_id' => $request->category,
            'type' => $type,
            'added_on' => now()
        ]);

        ExecuteLighthouseTest::dispatch($report);
    }

    
    public function send_mail_to(Request $request){
        SendLighthouseReportEmail::dispatch($request->report_id, $request->email, $request->status);
        return redirect()->route('admin.speedy.reports');
    }

    public function change_report_status($id){

        $report = LighthouseReport::firstWhere('id', $id);
        $report->lighthouse_status_id = 4;
        $report->readed_on = now();
        $report->save();

        return redirect()->away('https://www.roboamp.com');

    }


    public function preparing_knobs_images($report){
        $report = LighthouseReport::firstWhere('id', $report->id);

        foreach($report->flags as $flag){
            //generating With ROBOAMP knob charts
            $this->generate_knob($flag, 'amp', $flag->pivot->lighthouse_report_id, $flag->pivot->score);
            //generating Without ROBOAMP knob charts
            $this->generate_knob($flag, 'normal', $flag->pivot->lighthouse_report_id, $flag->pivot->score_normal);
        }
    }

    public function generate_knob($flag, $type, $report, $score){
        $root = URL::to('/');
        $color = ($type == 'amp') ?  '01c0c8' : 'f36e92'; 
        $url = $root.'/knob/'.$color.'/1.0/0/0.01/200/'.$score;
        KnobGeneration::dispatch($url, $flag, $type, $report);
    }

    
    public function preview_email($id){
        $data['user']=Auth::User();
        $data['report']=LighthouseReport::firstWhere('id', $id);
        $data['messages']=0;
        $data['comments']=0;
        $data['form_title']='Preview Report';
        
        return view('admin.lighthouseReports.preview.email',$data);
    }
}

resources/views/admin/lighthouseReports/create.blade.php
@extends('admin.forms')

@section('css_form')
    <link href="{{asset('dashboard_assets/dist/css/pages/bootstrap-switch.css')}}" rel="stylesheet">
@endsection

@section('form_fields')
    <div class="form-row">
        <div class="col-sm-12 col-lg-6">
            <div class="form-group">
                <label>Categories</label>
                <select class="custom-select" id="category" name="category" required>
                    <option value="">Choose...</option>
                @foreach ($categories as $category)
                    <option value="{{$category->id}}" {{ old('category') == $category->id ? 'selected' : ''  }}>{{$category->name}}</option>
                @endforeach
                </select>
                <div class="invalid-tooltip">Select a Category</div>
                <div class="valid-tooltip">Looks good!</div>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-12">
            <label for="urls">Urls</label>
            <textarea rows="7" class="form-control @error('txt_name')alert-danger @enderror" id="url" name="url" rows="5" required>{{old('url')}}</textarea>
            @error('name')
            <p class="text-danger">The URLs are required{{$errors->first('name')}}</p>
            @enderror
            <div class="invalid-tooltip">The URLs are required</div>
            <div class="valid-tooltip">Looks good!</div>
            
        </div>
    </div>
@endsection

@section('new_row')

@endsection
@section ('form_scripts_include')
    <script src="{{asset('dashboard_assets/node_modules/bootstrap-switch/bootstrap-switch.js')}}"></script>
    <script src="{{asset('dashboard_assets/js/pages/templates/create.js')}}"></script>

@endsection
<!-- code executed during init() main thread -->
@section('form_script')
    $('[data-toggle="switch"]').bootstrapSwitch();



@endsection

resources/views/admin/lighthouseReports/index.blade.php
@extends('admin.list')

@section('list')
<div class="clearfix">
    <a href="{{ route('admin.speedy.create') }}" class="btn btn-primary float-right">Execute Test</a>
</div>
<div class="table-responsive mt-3">
    <table class="table table-striped clickable-table" id="reports-table">
        <thead>
            <tr>
                <th>URL</th>
                <th>Category</th>
                <th>Type</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reports as $report)
            <tr data-target="{{$report->id}}">
                <td><a href="{{$report->url}}" target="_blank">{{$report->url}}</a></td>
                <td>{{$report->category->name}}</td>
                <td>{{$report->type}}</td>
                <td>
                    <span class="label label-{{$report->status->badge}}" id="label-<?= $report->id?>">{{$report->status->name}}</span>
                    @if ($report->status->id == 1)
                    <div class="spinner-border ml-3 spinner-<?= $report->id?>" role="status"><span class="sr-only">Loading...</span></div>
                    @endif
                </td>
            </tr>
            @endforeach
            
        </tbody>
    </table>
    
</div>
@endsection

@section('scripts')
    <link rel="stylesheet" type="text/css" href="{{asset('dashboard_assets/node_modules/datatables/jquery.dataTables.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('dashboard_assets/node_modules/toast-master/css/jquery.toast.css')}}">
    <script src="{{asset('dashboard_assets/node_modules/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('dashboard_assets/node_modules/datatables-responsive/js/dataTables.responsive.js')}}"></script>
    <script src="{{asset('dashboard_assets/node_modules/toast-master/js/jquery.toast.js')}}"></script>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script>
    $("#reports-table > tbody > tr").on("click",function(e){
        window.location = '/admin/speedy/show/'+$(this).data('target');
    });

    @if(count($reports) <= 10 )
    $('#reports-table').DataTable({
        searching: false,
        ordering:  false,
        paging: false
    });
    @else
    $('#reports-table').DataTable();
    @endif

    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var pusher = new Pusher('42821be930c76bca6620', {
      cluster: 'us2'
    });

    var channel = pusher.subscribe('LighthouseReport');
    channel.bind('App\\Events\\LighthouseReportUpdated', function(data) {
        $(".spinner-"+data.data.report.id).addClass("d-none");
        $("#label-"+data.data.report.id).attr("class", "");
        $("#label-"+data.data.report.id).text("");
        $("#label-"+data.data.report.id).attr("class", "label label-"+data.data.status.badge);
        $("#label-"+data.data.report.id).text(data.data.status.name);
        if(data.data.success){
            $.toast({
                heading: 'Lighthouse Report Update',
                text: data.data.message,
                position: 'top-right',
                loaderBg:'#00c292',
                icon: 'success',
                hideAfter: 3000,
                stack: false, 
            });
        }else{
            $.toast({
                heading: 'Lighthouse Report Update',
                text: data.data.message,
                position: 'top-right',
                loaderBg:'#e46a76',
                icon: 'error',
                hideAfter: 3000,
                stack: false, 
            });
        }
    });
    </script>
@endsection

resources/views/admin/lighthouseReports/knob.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('dashboard_assets')}}/images/favicon.png">
    <title>ROBOAMP - Control Panel</title>
    <!-- This page CSS -->
    <!-- This page CSS -->
    <!--<link href="{{--asset('dashboard_assets') --}}/node_modules/morrisjs/morris.css" rel="stylesheet"> -->
    <!-- Custom CSS -->
    <link href="{{asset('dashboard_assets')}}/css/style.min.css" rel="stylesheet">
    <!-- Dashboard 1 Page CSS -->
    <link href="{{asset('dashboard_assets')}}/css/pages/dashboard4.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    @yield('header_scrips')
    @yield('css')
</head>
  <body>
        <input data-plugin="knob" data-width="150" data-height="150" data-linecap="round" data-fgcolor="#01c0c8" value="0,85" data-min="0" data-max="1.1" data-step="0,01"  data-skin="tron" data-angleoffset="180" data-thickness=".2" readonly>

        <input data-plugin="knob" data-width="150" data-height="150" data-linecap="round" data-fgcolor="#fb9678" value="0,93"  data-min="0" data-max="1.1" data-step="0,01" data-skin="tron" data-angleoffset="180" data-thickness=".2" readonly>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->
<script src="{{asset('Axton/assets/node_modules/jquery/jquery-3.2.1.min.js')}}"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="{{asset('Axton/assets/node_modules/popper/popper.min.js')}}"></script>
<script src="{{asset('Axton/assets/node_modules/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('Axton/assets/node_modules/knob/jquery.knob.min.js')}}"></script>
<script type="text/javascript">

$(function() {
        $('[data-plugin="knob"]').knob();
    });

</script>
  </body>
</html>

resources/views/admin/lighthouseReports/show.blade.php
@extends('admin.list')

@section('list')
<div class="row">
    <div class="col-sm-12">
        <div class="card card-body">
            <h4 class="card-title">Lighthouse Report</h4>
            <h5 class="card-subtitle">URL: <a href="{{$report->url}}" target="_blank">{{$report->url}}</a> </h5>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label>Status</label>
                        <input type="text" class="form-control text-{{$report->status->badge}}" value="{{$report->status->name}} - @if($report->status->id == 3) {{ $report->readed_on }}@endif" readonly data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{$report->status->description}}">
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="example-email">Last Generated Report</span></label>
                        <input type="text" class="form-control" value="{{$report->added_on}}" readonly>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label>Category</label>
                        <input type="text" class="form-control" value="{{$report->category->name}}" readonly>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="example-email">Type</span></label>
                        <input type="text" class="form-control" value="{{$report->type}}" readonly>
                    </div>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Advantages of Roboamp</th>
                    <th scope="col">Score without ROBOAMP</th>
                    <th scope="col">Score with ROBOAMP</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ($report->flags as $flag)
                    <tr>
                        <td>{{$flag->name}}</td>
                        <td class="pl-5"><img src="{{ asset('knobs/generated/knob-normal-'.($flag->pivot->score_normal*100).'.png') }}" width="65" alt="{{$flag->pivot->score_normal}}"/></td>
                        <td class="pl-5"><img src="{{ asset('knobs/generated/knob-amp-'.($flag->pivot->score*100).'.png') }}" width="65" alt="{{$flag->pivot->score}}"/></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="row">
                @if($report->lighthouse_status_id != 5)
                <h5 class="card-subtitle">Send report </h5>
                <div class="col">
                    <div class="form-group">
                        <form method="POST" action="{{route('admin.speedy.mailto')}}" class="form-inline">
                            @csrf
                            <div class="form-group mb-2">
                                <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                                    <input type="hidden" value="{{ $report->id }}" name="report_id" id="report_id">
                                    <input type="hidden" value="3" name="status" id="status">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Send Mail</button>
                        </form>
                    </div>
                </div>
                @endif
                <div class="col">
                    <p class="text-center"><a href="{{url('admin/speedy/preview/email/'.$report->id)}}" class="btn btn-primary">Preview Email</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('scripts')
    <script>
    $('[data-toggle="tooltip"]').tooltip();
    </script>
@endsection